Src/ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using System.Threading.Tasks;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        [BindProperty]
        public CreateArticle Command { get; set; }
        public SelectList ArticleCategories { get; set; }

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public async Task OnGet()
        {
            ArticleCategories = new SelectList(await _articleCategoryApplication.GetArticleCategoriesAsync(), "Id", "Name");
        }

        public async Task<IActionResult> OnPost()
        {
            await _articleApplication.CreateAsync(Command);

            return RedirectToPage("./Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using System.Threading.Tasks;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        [BindProperty]
        public EditArticle Command { get; set; }
        public SelectList ArticleCategories { get; set; }

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public async Task OnGet(long id)
        {
            Command = await _articleApplication.GetDetailsAsync(id);
            ArticleCategories = new SelectList(await _articleCategoryApplication.GetArticleCategoriesAsync(), "Id", "Name");
        }

        public async Task<IActionResult> OnPost()
        {
            await _articleApplication.EditAsync(Command);

            return RedirectToPage("./Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/EditorPlan/Create.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanManagement.Application.Contracts.EditorPlan;

namespace ServiceHost.Areas.Administration.Pages.EditorPlan
{
    public class CreateModel : PageModel
    {
        private readonly IEditorPlanApplication _editorPlanApplication;

        public CreateModel(IEditorPlanApplication editorPlanApplication)
        {
            _editorPlanApplication = editorPlanApplication;
        }
        [BindProperty] public AddEditorPlan AddEditorPlan { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            var result = await _editorPlanApplication.CreateAsync(AddEditorPlan);
            return RedirectToPage("./Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/EditorPlan/Edit.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanManagement.Application.Contracts.EditorPlan;

namespace ServiceHost.Areas.Administration.Pages.EditorPlan
{
    public class EditModel : PageModel
    {
        private readonly IEditorPlanApplication _editorPlanApplication;

        public EditModel(IEditorPlanApplication editorPlanApplication)
        {
            _editorPlanApplication = editorPlanApplication;
        }
        [BindProperty] public EditEditorPlan EditEditorPlan { get; set; }
        public async Task OnGet(long id)
        {
            EditEditorPlan = await _editorPlanApplication.GetDetailsAsync(id);
        }

        [NeedsPermission(AccountPermissions.CreateAndEditFeature)]
        public async Task<IActionResult> OnPost()
        {
            var result = await _editorPlanApplication.EditAsync(EditEditorPlan);
            return RedirectToPage("./Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/EditorPlan/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Feature;
using AccountManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PlanManagement.Application.Contracts.EditorPlan;

namespace ServiceHost.Areas.Administration.Pages.EditorPlan
{
    public class IndexModel : PageModel
    {

        private readonly IEditorPlanApplication _editorPlanApplication;

        public IndexModel(IEditorPlanApplication editorPlanApplication)
        {
            _editorPlanApplication = editorPlanApplication;
        }

        public List<EditorPlanViewModel> EditorPlans { get; set; }

        public async Task OnGet()
        {
            EditorPlans = await _editorPlanApplication.GetListAsync();
        }


        [NeedsPermission(AccountPermissions.CreateAndEditFeature)]
        public async Task<IActionResult> OnGetRemove(long id)
        {
            await _editorPlanApplication.RemoveAsync(id);
            return RedirectToPage("./Index");
        }
        [NeedsPermission(AccountPermissions.CreateAndEditFeature)]
        public async Task<IActionResult> OnGetRestore(long id)
        {
            await _editorPlanApplication.RestoreAsync(id);
            return RedirectToPage("./Index");
        }

    }
}

Src/ServiceHost/Areas/Administration/Pages/Role/Create.cshtml.cs
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using AccountManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Role
{
    public class CreateModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        [BindProperty]
        public CreateRole Command { get; set; }

        [NeedsPermission(AccountPermissions.CreateAndEditRole)]
        public void OnGet()
        {
        }

        [NeedsPermission(AccountPermissions.CreateAndEditRole)]
        public IActionResult OnPost()
        {
            _roleApplication.CreateAsync(Command);
            return RedirectToPage("Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/Role/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using AccountManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Role
{
    public class EditModel : PageModel
    {
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;
        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        [BindProperty]
        public EditRole Command { get; set; }

        public List<SelectListItem> Permissions = new List<SelectListItem>();

        [NeedsPermission(AccountPermissions.CreateAndEditRole)]
        public async Task OnGet(long id)
        {
            Command = await _roleApplication.GetDetailsAsync(id);
            var permissions = new List<PermissionDto>();

            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    permissions.AddRange(value);

                    var gruop = new SelectListGroup {Name = key};
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = gruop
                        };

                        if (Command.MappedPermissions.Any(v => v.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);
                    }
                }
            }
        }


        [NeedsPermission(AccountPermissions.CreateAndEditRole)]
        public async Task<IActionResult> OnPost()
        {
            await _roleApplication.EditAsync(Command);

            return RedirectToPage("Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/EditorPlan/Create.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.EditorPlan.CreateModel
@{

}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد پلن جدید</h4>
</div>

<form
      method="post"
      enctype="multipart/form-data">
    <div class="modal-body">
            <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="AddEditorPlan.Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="AddEditorPlan.Title" onchange="makeSlug('AddEditorPlan_Title', 'AddEditorPlan_PictureAlt'), makeSlug('AddEditorPlan_Title', 'AddEditorPlan_PictureTitle')">
                    <span asp-validation-for="AddEditorPlan.Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="AddEditorPlan.ChatUploadSizeLimit" class="control-label"> سایز اپلود فایل چت(byte)</label>
                    <input type="number" class="form-control" asp-for="AddEditorPlan.ChatUploadSizeLimit">
                    <span asp-validation-for="AddEditorPlan.ChatUploadSizeLimit" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="AddEditorPlan.PortfolioUploadSizeLimit" class="control-label"> سایز اپلود فایل نمونه کار(byte)</label>
                    <input type="number" class="form-control" asp-for="AddEditorPlan.PortfolioUploadSizeLimit">
                    <span asp-validation-for="AddEditorPlan.PortfolioUploadSizeLimit" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="AddEditorPlan.ExpireDays" class="control-label">تعداد روز ها</label>
                    <input type="number" class="form-control" asp-for="AddEditorPlan.ExpireDays">
                    <span asp-validation-for="AddEditorPlan.ExpireDays" class="error"></span>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="AddEditorPlan.VipProjectOfferCount" class="control-label">تعداد پیشنهاد پروژه ویژه</label>
                    <input type="number" class="form-control" asp-for="AddEditorPlan.VipProjectOfferCount">
                    <span asp-validation-for="AddEditorPlan.VipProjectOfferCount" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="AddEditorPlan.Price" class="control-label">قیمت</label>
                    <input type="number" class="form-control" asp-for="AddEditorPlan.Price">
                    <span asp-validation-for="AddEditorPlan.Price" class="error"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="AddEditorPlan.Description" class="control-label">توضیحات</label>
                    <textarea rows="14" class="form-control autogrow" id="BodyContent" asp-for="AddEditorPlan.Description"
                              style="overflow: hidden; word-wrap: break-word; resize: vertical;"></textarea>
                    <span asp-validation-for="AddEditorPlan.Description" class="error"></span>
                </div>
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

<script src="https://cdn.tiny.cloud/1/xx7w4yhewzptxxt67fpih1f1wu93ajadjc5q7e1dr7qvq37a/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#BodyConten',
        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
    });
</script>

Src/ServiceHost/Areas/Administration/Pages/EditorPlan/Edit.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.EditorPlan.EditModel
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش پلن: @Model.EditEditorPlan.Title</h4>
</div>

<form
      method="post">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="EditEditorPlan.Title" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="EditEditorPlan.Title" onchange="makeSlug('EditEditorPlan_Title', 'EditEditorPlan_PictureAlt'), makeSlug('EditEditorPlan_Title', 'EditEditorPlan_PictureTitle')">
                    <span asp-validation-for="EditEditorPlan.Title" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="EditEditorPlan.ChatUploadSizeLimit" class="control-label"> سایز اپلود فایل چت(byte)</label>
                    <input type="number" class="form-control" asp-for="EditEditorPlan.ChatUploadSizeLimit">
                    <span asp-validation-for="EditEditorPlan.ChatUploadSizeLimit" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="EditEditorPlan.PortfolioUploadSizeLimit" class="control-label"> سایز اپلود فایل نمونه کار(byte)</label>
                    <input type="number" class="form-control" asp-for="EditEditorPlan.PortfolioUploadSizeLimit">
                    <span asp-validation-for="EditEditorPlan.PortfolioUploadSizeLimit" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="EditEditorPlan.ExpireDays" class="control-label">تعداد روز ها</label>
                    <input type="number" class="form-control" asp-for="EditEditorPlan.ExpireDays">
                    <span asp-validation-for="EditEditorPlan.ExpireDays" class="error"></span>
                </div>
            </div>

            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="EditEditorPlan.VipProjectOfferCount" class="control-label">تعداد پیشنهاد پروژه ویژه</label>
                    <input type="number" class="form-control" asp-for="EditEditorPlan.VipProjectOfferCount">
                    <span asp-validation-for="EditEditorPlan.VipProjectOfferCount" class="error"></span>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="EditEditorPlan.Price" class="control-label">قیمت</label>
                    <input type="number" class="form-control" asp-for="EditEditorPlan.Price">
                    <span asp-validation-for="EditEditorPlan.Price" class="error"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group no-margin">
                    <label asp-for="EditEditorPlan.Description" class="control-label">توضیحات</label>
                    <textarea rows="14" class="form-control autogrow" id="BodyContent" asp-for="EditEditorPlan.Description"
                              style="overflow: hidden; word-wrap: break-word; resize: vertical;"></textarea>
                    <span asp-validation-for="EditEditorPlan.Description" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="EditEditorPlan.Id" value="@Model.EditEditorPlan.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

<script src="https://cdn.tiny.cloud/1/xx7w4yhewzptxxt67fpih1f1wu93ajadjc5q7e1dr7qvq37a/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
        selector: '#BodyContent',
        plugins: 'a11ychecker advcode casechange export formatpainter linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tinycomments tinymcespellchecker',
        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter pageembed permanentpen table',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
    });
</script>

Src/ServiceHost/Areas/Administration/Pages/EditorPlan/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.EditorPlan.IndexModel
@{
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title pull-right">@ViewData["title"]</h4>
            <p class="pull-left">
                <a class="btn btn-success btn-lg" asp-page="./Create">ایجاد پلن جدید</a>
            </p>
        </div>
    </div>


    <div class="row" id="ProductCategoriesDiv">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">لیست پلن های ادیتور (@Model.EditorPlans.Count)</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <table id="datatable" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>عنوان</th>
                                        <th>قیمت</th>
                                        <th>تاریخ ایجاد</th>
                                        <th>عملیات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.EditorPlans)
                                    {

                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Title</td>
                                            <td>@item.Price</td>
                                            <td>@item.CreationDate</td>
                                            <td>
                                                <a class="btn btn-warning waves-effect waves-light m-b-5"
                                                   asp-page="./Edit" asp-route-id="@item.Id">
                                                    <i class="fa fa-edit"></i> ویرایش
                                                </a>
                                                @if (item.IsRemoved)
                                                {
                                                    <a asp-page-handler="Restore" asp-route-id="@item.Id" class="btn btn-danger">غیر فعال</a>
                                                }
                                                else
                                                {
                                                    <a asp-page-handler="Remove" asp-route-id="@item.Id" class="btn btn-success">فعال</a>
                                                }
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>