Src/ServiceHost/Areas/Administration/Pages/Wallets/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Project;
using AccountManagement.Application.Contracts.ProjectOffer;
using CommentManagement.Application.Contracts.Comment;
using CommentManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WalletManagement.Application.Contracts.Wallet;

namespace ServiceHost.Areas.Administration.Pages.Wallets
{
    public class IndexModel : PageModel
    {
        private readonly IWalletApplication _walletApplication;

        public IndexModel(IWalletApplication walletApplication)
        {
            _walletApplication = walletApplication;
        }

        [TempData]
        public string Message { get; set; }

        public List<WalletViewModel> Wallets { get; set; }


        public async Task OnGet(string title)
        {
            Wallets = await _walletApplication.GetAllAsync();
        }


        public async Task<IActionResult> OnGetSettlement(Guid id)
        {
            await _walletApplication.SettlementAsync(id);
            return RedirectToPage("./Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/Wallets/Transactions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WalletManagement.Application.Contracts.Wallet;

namespace ServiceHost.Areas.Administration.Pages.Wallets
{
    public class TransactionsModel : PageModel
    {
        private readonly IWalletApplication _walletApplication;

        public WalletViewModel Wallet { get; set; }
        public TransactionsModel(IWalletApplication walletApplication)
        {
            _walletApplication = walletApplication;
        }

        public async Task OnGet(Guid Id)
        {
            Wallet = await _walletApplication.GetWalletByIdAsync(Id);
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/Wallets/Index.cshtml
@page
@using CommentManagement.Infrastructure.Configuration.Permissions
@model ServiceHost.Areas.Administration.Pages.Wallets.IndexModel
@{
}

@{
    ViewData["title"] = "مدیریت کیف پول ها";
}


<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کیف پول ها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>شناسه کاربر</th>
                                    <th>نام کاربر</th>
                                    <th>اعتبار جاری</th>
                                    <th>درخواست واریز</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var wallet in Model.Wallets)
                                {
                                    <tr>
                                        <td>@wallet.Id</td>
                                        <td>@wallet.AccountId</td>
                                        <td>@wallet.AccountName</td>
                                        <td>@wallet.CurrentCredit.ToString("N0")</td>
                                        <td><span class="text-@(wallet.IsAskedForSettlement ? "success" : "danger")">@(wallet.IsAskedForSettlement ? "درخواست شده" : "درخواست نشده")</span></td>
                                        <td>
                                            <a asp-page="./Index" asp-page-handler="Settlement" asp-route-id="@wallet.Id"
                                           class="btn btn-success">واریز کردن</a>
                                        </td>
                                        <td>
                                            <a asp-page="./Transactions" asp-route-id="@wallet.Id"
                                           class="btn btn-success">تراکنش ها</a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#datatable').dataTable();
        });
    </script>
}

Src/ServiceHost/Areas/Administration/Pages/Wallets/Transactions.cshtml
@page "{Id}"
@model ServiceHost.Areas.Administration.Pages.Wallets.TransactionsModel

@{
    ViewData["title"] = "مدیریت کیف پول ها";
}


<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست تراکنش ها</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>نام کاربری دریافت کننده</th>
                                    <th>مبلغ</th>
                                    <th>توضیحات</th>
                                    <th>نوع</th>
                                    <th>نتیجه عملیات</th>
                                    <th>تاریخ</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Wallet.Transactions == null || Model.Wallet.Transactions.Count == 0)
                                {
                                    <tr>
                                        <td>خالی</td>
                                        <td>خالی</td>
                                        <td>خالی</td>
                                        <td>خالی</td>
                                        <td>خالی</td>
                                        <td>خالی</td>
                                    </tr>
                                }
                                else
                                {
                                    @foreach (var transaction in Model.Wallet.Transactions)
                                    {
                                        <tr>
                                            <td>@transaction.ReceiverAccountName</td>
                                            <td>@transaction.Amount.ToString("N0")</td>
                                            <td>@transaction.Description</td>
                                            <td>
                                                <span class="text-@(transaction.IsDeposit ? "success" : "danger")">@(transaction.IsDeposit ? "دریافت" : "برداشت")</span>
                                            </td>
                                            <td>

                                                <span class="text-@(transaction.IsSuccess ? "success" : "danger")">@(transaction.IsSuccess ? "موفق" : "ناموفق")</span>
                                            </td>
                                            <td>@transaction.CreationDate</td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#datatable').dataTable();
        });
    </script>
}