Src/ServiceHost/Areas/Administration/Pages/JobOffers/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.JobOffer;
using AccountManagement.Application.Contracts.Project;
using AccountManagement.Application.Contracts.ProjectOffer;
using CommentManagement.Application.Contracts.Comment;
using CommentManagement.Infrastructure.Configuration.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.JobOffers
{
    public class IndexModel : PageModel
    {
        private readonly IJobOfferApplication _jobOfferApplication;

        public IndexModel(IJobOfferApplication reviewApplication)
        {
            _jobOfferApplication = reviewApplication;
        }

        [TempData]
        public string Message { get; set; }

        public List<JobOfferViewModel> Projects { get; set; }


        public async Task OnGet(string title)
        {
            Projects = await _jobOfferApplication.SearchAsync(title);
        }


        [NeedsPermission(CommentPermissions.ConfirmAndCancelComment)]
        public async Task<IActionResult> OnGetConfirm(long id)
        {
           await _jobOfferApplication.AcceptAsync(id);

            return RedirectToPage("./Index");
        }
    }
}

Src/ServiceHost/Areas/Administration/Pages/JobOffers/Index.cshtml
@page
@using CommentManagement.Infrastructure.Configuration.Permissions
@model ServiceHost.Areas.Administration.Pages.JobOffers.IndexModel
@{
}

@{
    ViewData["title"] = "مدیریت نظر ها";
}


<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در نام ها</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" for="title"></label>
                        <input class="form-control" placeholder="عنوان" id="title" name="title">
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست پیشنهاد های کاری</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عنوان</th>
                                    <th>توضیح</th>
                                    <th>هزینه</th>
                                    <th> ادیتور</th>
                                    <th>کارفرما</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var review in Model.Projects)
                                {
                                    <tr>
                                        <td>@review.Id</td>
                                        <td>@review.Title</td>
                                        <td>@review.Description</td>
                                        <td>@review.Price</td>
                                        <td>@review.EditorName</td>
                                        <td>@review.EmployerName</td>
                                        <td class="text-center">
                                            @if (review.IsAccept)
                                            {
                                                <span class="text-success">تایید شده</span>
                                            }

                                            @if (!review.IsAccept && review.IsCancel)
                                            {
                                                <span class="text-danger">رد شده</span>
                                            }
                                        </td>
                                        <td>
                                            <a permission="@CommentPermissions.ConfirmAndCancelComment" asp-page="./Index" asp-page-handler="Confirm" asp-route-id="@review.Id"
                                           class="btn btn-success">پذیرفتن</a>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#datatable').dataTable();
        });
    </script>
}